// Importación de fuentes optimizadas directamente desde Google Fonts en Next.js
import { Geist, Geist_Mono } from "next/font/google";
// Importación de la hoja de estilos global comentada anteriormente
import "./globals.css";

// Configuración de la fuente Sans-serif principal
const geistSans = Geist({
  variable: "--font-geist-sans", // Define una variable CSS para usarla en Tailwind
  subsets: ["latin"],
});

// Configuración de la fuente Monoespaciada
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Objeto de metadatos crucial para el SEO. Define el título y descripción de la app.
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Componente RootLayout: Es la envoltura principal de toda la aplicación.
// Define la estructura básica del documento HTML y el Body.
export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      // Inyecta las variables de las fuentes y aplica clases base de Tailwind
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      {/* El body ocupa al menos el alto total de la pantalla y usa Flexbox en columna */}
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}